### ISSUE TITLE
Copyright year

### ISSUE THREAD

**Issue by huntantr** [lluissm/license-header-checker#49]
When using this tool to check for a copyright, is there anyway to make the year be less specific. We have source code that hasn't changed in years, so it won't have a 2022 year in it, but a 2020. 

Thanks.

**Comment by lluissm** [comment]
Hello @huntantr,

Can you please describe the concrete use case you want to achieve so I can better help you?

**Comment by hatvik** [comment]
I assume he wants unchanged files to retain the original copyright year.

example.h with `copyright 2020`, should **remain 2020 until example.h is changed.**

If example.h is changed in 2022, then it should change to `copyright 2020, 2022`

**Comment by lluissm** [comment]
If the `-r` flag is not supplied, the tool will not replace the copyright header if there is already one. You could just use `-a` to only add to the ones that do not have any.

But then, if you need to update the year in the copyright header after modifying the file, you should do it manually when you update the file as the tool does not really know when you modified the file.

**Comment by ramanNarasimhan77** [comment]
@lluissm  
In my case the `-a` flag added the new license to the files that already had a license.
I was adding `license` to yaml file with sample header shown below

```yaml
#
# COPYRIGHT MyCompany 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# MyCompany Inc. The programs may be used and/or copied only with written
#
# permission from MyCompany Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#
````

I updated 2022 to 2023 in my license-header-text file, and the tool added it also to this file.

Similar issue would also occur for shell scripts I suppose as the Copyright comment would be in a block where every line starts with '#'

I think this happens because  yaml uses `#` for comments, but this code https://github.com/lluissm/license-header-checker/blob/master/pkg/process/process_header.go#L39 expects `/* */` comment blocks
